### ISSUE TITLE
Dependency clashes

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#209]
cc @jeromekelleher, convo continued from [this one](https://github.com/tskit-dev/msprime/issues/835) in the msprime repo.

I found that after installing `stdpopsim`, I was no longer able to run `msprime` on it's own - I was getting the following message:

```
Python 3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/msprime/__init__.py", line 24, in <module>
    import tskit
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tskit/__init__.py", line 30, in <module>
    from tskit.provenance import __version__  # NOQA
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/tskit/provenance.py", line 31, in <module>
    import jsonschema
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/jsonschema/exceptions.py", line 152, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'
>>> 
```
After googling [the error](https://stackoverflow.com/questions/49228744/attributeerror-module-attr-has-no-attribute-s), it seemed like this problem was to do with the fact that msprime relies on a function called `attr.*` that is (confusingly) located in a package called `attrs`. If you have both `attr` and `attrs`, python won't look in the correct module for the necessary function. However, we also can't remove `attr`, because this is needed for `stdpopsim`:

```
6200D-132482-M:aus-ABC gtsambos$ stdpopsim --help
Traceback (most recent call last):
  File "/Users/gtsambos/miniconda3/bin/stdpopsim", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/gtsambos/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'attr' distribution was not found and is required by stdpopsim
```
I'm guessing this wouldn't be a problem specific to me -- has anyone else run into this? Any ideas for how we might prevent other users having this issue?

**Comment by jeromekelleher** [comment]
Yes, crud, this is my fault. I put the ``attr`` package as a requirement in setup.py instead of ``attrs``. Will fix ASAP
