### ISSUE TITLE
Network issues on Appveyor

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#240]
In #169 we started to see network errors for downloading genetic maps on Appveyor. Looks like the server thinks we're using it too much:
```
======================================================================
540ERROR: test_recombination_rates (tests.test_homo_sapiens.TestGenome)
541----------------------------------------------------------------------
542Traceback (most recent call last):
543  File "C:\projects\stdpopsim\tests\test_homo_sapiens.py", line 68, in test_recombination_rates
544    contig = species.get_contig(chrom.id, genetic_map=genetic_map)
545  File "C:\projects\stdpopsim\stdpopsim\species.py", line 136, in get_contig
546    recomb_map = gm.get_chromosome_map(chrom.id)
547  File "C:\projects\stdpopsim\stdpopsim\genetic_maps.py", line 144, in get_chromosome_map
548    self.download()
549  File "C:\projects\stdpopsim\stdpopsim\genetic_maps.py", line 110, in download
550    urllib.request.urlretrieve(self.url, filename=download_file)
551  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 247, in urlretrieve
552    with contextlib.closing(urlopen(url, data)) as fp:
553  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 222, in urlopen
554    return opener.open(url, data, timeout)
555  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 525, in open
556    response = self._open(req, data)
557  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 543, in _open
558    '_open', req)
559  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 503, in _call_chain
560    result = func(*args)
561  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 1360, in https_open
562    context=self._context, check_hostname=self._check_hostname)
563  File "C:\Miniconda37-x64\envs\testenv\lib\urllib\request.py", line 1319, in do_open
564    raise URLError(err)
565urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
566-------------------- >> begin captured logging << --------------------
567stdpopsim.species: DEBUG: Getting map for chr1 from HapmapII_GRCh37
568stdpopsim.genetic_maps: DEBUG: Checking species cache directory C:\Users\appveyor\AppData\Local\popgensims\stdpopsim\Cache\genetic_maps\homsap
569stdpopsim.genetic_maps: INFO: Downloading genetic map 'HapmapII_GRCh37' from https://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/working/20110106_recombination_hotspots/HapmapII_GRCh37_RecombinationHotspots.tar.gz
570--------------------- >> end captured logging << ---------------------

```

Hopefully this is intermittent and just a result of the recent (excellent!) jump in PR activity.

**Comment by jeromekelleher** [comment]
This seems to have gone away, so closing.
